### PR TITLE
Fix bug in pinned_memory_resource with CCCL 3.1.x.

### LINKED ISSUE #2057: [BUG] pinned_memory_resource (host MR) fails with CCCL 3.1.0+
**Describe the bug**
PR #2017 added build-time support for CCCL 3.1.0. In downstream testing, I found that cuVS failed to compile:

```
/home/coder/cuvs/cpp/src/core/c_api.cpp: In lambda function:
/home/coder/cuvs/cpp/src/core/c_api.cpp:171:31: error: no matching function for call to 'rmm::mr::pinned_memory_resource::allocate(const size_t&)'
  171 |     *ptr = pinned_mr->allocate(bytes);
      |            ~~~~~~~~~~~~~~~~~~~^~~~~~~
In file included from /home/coder/cuvs/cpp/src/core/c_api.cpp:33:
/home/coder/rmm/cpp/include/rmm/mr/host/pinned_memory_resource.hpp:166:9: note: candidate: 'void* rmm::mr::pinned_memory_resource::allocate(rmm::cuda_stream_view, std::size_t, std::size_t)'
  166 |   void* allocate(cuda_stream_view stream, std::size_t bytes, std::size_t alignment)
      |         ^~~~~~~~
/home/coder/rmm/cpp/include/rmm/mr/host/pinned_memory_resource.hpp:166:9: note:   candidate expects 3 arguments, 1 provided
/home/coder/cuvs/cpp/src/core/c_api.cpp: In lambda function:
/home/coder/cuvs/cpp/src/core/c_api.cpp:177:70: error: no matching function for call to 'rmm::mr::pinned_memory_resource::deallocate(void* const&, const size_t&)'
  177 |   return cuvs::core::translate_exceptions([=] { pinned_mr->deallocate(ptr, bytes); });
      |                                                 ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/coder/rmm/cpp/include/rmm/mr/host/pinned_memory_resource.hpp:180:8: note: candidate: 'void rmm::mr::pinned_memory_resource::deallocate(rmm::cuda_stream_view, void*, std::size_t, std::size_t)'
  180 |   void deallocate(cuda_stream_view stream, void* ptr, std::size_t bytes, std::size_t alignment)
      |        ^~~~~~~~~~
/home/coder/rmm/cpp/include/rmm/mr/host/pinned_memory_resource.hpp:180:8: note:   candidate expects 4 arguments, 2 provided
```

After some investigation, I found that the changes in this block triggered C++ inheritance name hiding.

https://github.com/rapidsai/rmm/blob/278d5596227df7ba91f59b056f1dfe34d6af68f7/cpp/include/rmm/mr/host/pinned_memory_resource.hpp#L152-L185

The `pinned_memory_resource` defines new `allocate` overloads to be compatible with CCCL 3.1.0+ memory resource concepts. However, the previous `allocate(bytes)` is hidden.

This should have been caught in RMM tests. I am working on a PR that fixes the bug (with `using host_memory_resource::allocate` to explicitly allow the parent's overloads) and add tests that will catch this for the future.

### PR DESCRIPTION
**Pull request by bdice**
## Description
Closes #2057.

This fix only affects builds with CCCL 3.1.0+.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bdice** [comment]
I am recommending this for a merge during code freeze because this bug affects downstream builds with CCCL 3.1.0, which we would like to support at build time in RAPIDS 25.10. We won't be upgrading RAPIDS to CCCL 3.1.0 until the 25.12 release, but having build-time support for CCCL 3.1.0 will be useful for future builds based on this release.

The risk of breaking things is very low because the change is only active when CCCL 3.1.0 or higher is available.

File: cpp/include/rmm/mr/host/pinned_memory_resource.hpp [hunk 1]
```diff
@@ -152,6 +152,12 @@ class pinned_memory_resource final : public host_memory_resource {
 #if CCCL_MAJOR_VERSION > 3 || (CCCL_MAJOR_VERSION == 3 && CCCL_MINOR_VERSION >= 1)
 
  public:
+  // Explicitly inherit the allocate and deallocate functions from the host_memory_resource class.
+  // Due to inheritance and name hiding rules, we need to declare these with "using" when we
+  // override allocate and deallocate for CCCL 3.1.0+ compatibility.
+  using host_memory_resource::allocate;
+  using host_memory_resource::deallocate;
+
```
Comment (bdice) [inline cpp/include/rmm/mr/host/pinned_memory_resource.hpp:160]: Reviewers: these lines are the fix. If you prefer to limit the diff, I can punt on adding the tests until `branch-25.12`. Let me know if you'd prefer that.

**Review by wence- — APPROVED** [review]
Approving C++
